accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name = 'user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('follow/<int:user_id>/' , views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('notifications/', views.NotificationListView.as_view(), name='notification_list'),


    
]

zab/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path ('posts', include('posts.urls')),
    
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from .managers import UserManager



class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30, unique=True)
    full_name = models.CharField(max_length=70)
    phone_number = models.CharField(max_length=15, unique=True)
    profile_picture = models.ImageField(upload_to="blog/", blank=True, null=True)
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=[("male", "Male"), ("female", "Female"), ("other", "Other")], blank=True)
    date_joined = models.DateTimeField(default=timezone.now)
    friends = models.ManyToManyField('self', symmetrical=True)
    blocked_users = models.ManyToManyField('self')
    website = models.URLField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'username', 'full_name']

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin



class Relation(models.Model):
    from_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.from_author} follows {self.to_author}"
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/', null=True, blank=True, default='static/img/defult.jpg')
    full_name = models.CharField(max_length=100, default='The author of Zab')
    age = models.PositiveSmallIntegerField(null=True, blank=True, validators=[
        MinValueValidator(1, message='Age must be at least 1.'),
        MaxValueValidator(100, message='Age cannot exceed 100.'),
    ])
    bio = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.user.username
    


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=100)
    link = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    viewed  = models.BooleanField(default=False)

    def __str__(self):
        return self.message
        

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Profile
from .models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm





class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email', 'phone_number', 'full_name')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
			raise ValidationError('passwords dont match')
		return cd['password2']

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class UserChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField(help_text="you can change password using <a href=\"../password/\">this form</a>.")

	class Meta:
		model = User
		fields = ('email', 'phone_number', 'full_name', 'profile_picture', 'bio', 'location', 'date_of_birth', 'gender', 'website', 'is_active', 'is_admin')


class UserRegistrationForm(forms.Form):
	full_name = forms.CharField( widget=forms.TextInput(attrs={'class':'form-control'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	phone_number =forms.CharField(label='phone number', widget=forms.NumberInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

 
	def clean_email(self):
		email = self.cleaned_data['email']
		user = User.objects.filter(email=email).exists()
		if user:
			raise ValidationError('this email already exists')
		return email

	def clean(self):
		cd = super().clean()
		p1 = cd.get('password1')
		p2 = cd.get('password2')

		if p1 and p2 and p1 != p2:
			raise ValidationError('password must match')
		

class UserLoginForm(forms.Form):
	username = forms.CharField(label='Email or username' ,widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))


class EditUserForm(forms.ModelForm):
	email = forms.EmailField()
	
	class Meta:
		model = Profile
		fields = ('full_name', 'image', 'age', 'bio')

	def clean_age(self):
		age = self.cleaned_data.get('age')
		if age is not None and (age < 1 or age > 100):
			raise forms.ValidationError("Age must be between 1 and 100.")
		return age



class UserPasswordResetForm(PasswordResetForm):
	email = forms.EmailField(label='email address', widget=forms.TextInput(attrs={'class':'form-control'}))


class CustomPasswordResetConfirmForm(SetPasswordForm):
    """
    Custom form for password reset confirmation.
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }

    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text="Enter your new password.",
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text="Enter the same password as above, for verification.",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update({'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'placeholder': 'Confirm New Password'})

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )

        return cleaned_data
		

# class UserEnterNewPassword(SetPasswordForm):
	# password = forms.CharField(label='New password',  widget=forms.PasswordInput(attrs={'class':'form-control'}))
	# cpassword = forms.CharField(label='Confirm password',  widget=forms.PasswordInput(attrs={'class':'form-control'}))

	# def __init__(self, user, *args, **kwargs):
		# super(UserEnterNewPassword, self).__init__(user, *args, **kwargs)

# from django import forms
# from django.contrib.auth.forms import SetPasswordForm

accounts/views.py
from typing import Any
from django import http
from .models import User,Relation, Notification
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http.response import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm, EditUserForm, UserPasswordResetForm, CustomPasswordResetConfirmForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from posts.models import Post
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_decode
from webpush import send_user_notification
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView






class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user_registration_info = {
                'phone_number': form.cleaned_data['phone_number'],
                'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'username': form.cleaned_data['username'],
                'password': form.cleaned_data['password1'],  # Use 'password1' field
            }

            # Create a new User instance using your custom user manager
            user = User.objects.create_user(
                email=user_registration_info['email'],
                username=user_registration_info['username'],
                full_name=user_registration_info['full_name'],
                phone_number=user_registration_info['phone_number'],
                password=user_registration_info['password']
            )

            # Redirect to user login or any other appropriate view
            return redirect('accounts:user_login')

        return render(request, self.template_name, {'form': form})
		    



class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'
    success_url = 'home:home'

    def setup(self, request, *args, **kwargs):
        self.next= request.GET.get('next', None)
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                if self.next:
                    return redirect(self.next)
                return redirect(self.success_url)
            else:
                messages.error(request, 'Username or password is incorrect.')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('home:home')


class UserProfileView(View):
    @method_decorator(login_required(login_url='/accounts/login/'))
    def get(self, request, user_id):
        is_following = False
        user = get_object_or_404(User, pk=user_id)
        posts = Post.objects.filter(author=user)
        relation= Relation.objects.filter(from_author=request.user, to_author=user )
        if relation.exists():
            is_following= True
        return render(request, 'accounts/profile.html', {'user': user, 'posts': posts, 'is_following':is_following})


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        to_user = get_object_or_404(User, id=user_id)
        from_user = request.user

        if to_user != from_user and not Relation.objects.filter(from_author=from_user, to_author=to_user).exists():
            Relation(from_author=from_user, to_author=to_user).save()
            messages.success(request, f'You are now following {to_user.username}.')
        else:
            messages.error(request, 'Unable to follow this user.')

        return redirect('accounts:user_profile', user_id=to_user.id)

class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        to_user = get_object_or_404(User, id=user_id)
        from_user = request.user

        try:
            relation = Relation.objects.get(from_author=from_user, to_author=to_user)
            relation.delete()
            messages.success(request, f'You have unfollowed {to_user.username}.')
        except Relation.DoesNotExist:
            messages.error(request, 'Unable to unfollow this user.')

        return redirect('accounts:user_profile', user_id=to_user.id)
    

class EditUserView(LoginRequiredMixin, View):
    form_class = EditUserForm

    def get (self, request):
        form = self.form_class(instance=request.user.profile, initial={'email':request.user.email})
        return render(request, 'accounts/edit_profile.html', {'form':form})
    
    def post (self,request):
        form =self.form_class(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(request, 'edit profile successfully', extra_tags='success')
        return redirect('accounts:user_profile', request.user.id)


  
class UserPasswordResetView(auth_views.PasswordResetView):
    form_class = UserPasswordResetForm
    template_name = 'accounts/input_email.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'

class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
	template_name = 'accounts/send_email_reset.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    form_class = CustomPasswordResetConfirmForm  # Use the custom form
    template_name = 'accounts/input_password_form.html'
    success_url = reverse_lazy('accounts:password_reset_complete')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['custom_action_url'] = reverse_lazy('accounts:password_reset_confirm', kwargs={'uidb64': self.kwargs['uidb64'], 'token': self.kwargs['token']})
        return context



    
class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
	template_name = 'accounts/password_change_message.html'


class NotificationListView(ListView):
    model = Notification
    template_name = 'accounts/notifications.html'
    context_object_name = 'notifications'





        

 
		   

accounts/templates/accounts/Login.html
{% load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css\login.css' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@1,500&family=Josefin+Sans&family=Poppins:ital,wght@0,400;0,700;1,300&family=Roboto:ital,wght@0,400;1,500&family=Rubik+Pixels&family=Yanone+Kaffeesatz&display=swap"
        rel="stylesheet">
    <meta name="viewport" content="width=\, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Login</title>
</head>

<body>
    <div class="login">
        <h1 class="text-center">Welcome Back!</h1>
        <hr>
        <form method="post" action="{% url 'accounts:user_login' %}" novalidate>
            {% csrf_token %}
            {{form.as_p}}

            <input class="btn btn-success w-100 rounded-pill " type="submit" value="Login">
            <a href="{% url 'accounts:reset_password' %}" class="mt-2">Have you forgotten your password?</a>

        </form>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>


</body>

</html>

accounts/templates/accounts/Profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
      name="viewport"
    />
    <title>Profile</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    />
  </head>
  <body>
    {% if messages %}
    <div class="container mt-4" id="messages-container">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% elif message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    </div>
    <div class="container py-5">
      <div class="row">
        <div class="col-md-3">
          <!-- User Photo -->
          <div class="bg-white shadow rounded-lg mb-4">
            <div class="text-center pt-3">
              {% if user.profile.image %}
                <img
                  src="{{ user.profile.image.url }}"
                  alt="User"
                  class="img-thumbnail"
                />
              {% else %}
                <!-- Display a default photo or a message when 'image' is not set -->
                <img
                  src="{% static 'img/defult.jpg' %}"
                  alt="Default Profile Photo"
                  class="img-thumbnail"
                />
                <!-- Alternatively, you can show a message -->
                <!-- <p>No profile photo uploaded</p> -->
              {% endif %}
            </div>
            <div class="p-3">
              <h4 class="text-center">{{ user.username }}</h4>
              <!-- User Stats (Total Posts, Followers, etc.) -->
              <ul class="list-unstyled">
                <li>Total Posts: 2</li>
                <li>Followers: 1000</li>
                <!-- Follow/Unfollow buttons here -->
              </ul>
              {% if user == request.user %}
                <!-- Show Edit Profile link if the user is viewing their own profile -->
                <a class="btn btn-outline-dark mt-3" href="{% url 'accounts:edit_user' %}">Edit Profile</a>
              {% else %}
                {% if not is_following %}
                  <!-- Show Follow button if the current user is not following the profile user -->
                  <a class="btn btn-primary mt-3" href="{% url 'accounts:user_follow' user.id %}">Follow</a>
                {% else %}
                  <!-- Show Unfollow button if the current user is following the profile user -->
                  <a class="btn btn-danger mt-3" href="{% url 'accounts:user_unfollow' user.id %}">Unfollow</a>
                {% endif %}
              {% endif %}
            </div>
          </div>
    
          <!-- Display Family Name, Age, and Biography -->
          <div class="bg-white shadow rounded-lg mb-4">
            <div class="p-3">
              <p class="text-center">Full name: {{ user.profile.full_name }}<p></p>
              <p class="text-center">Age: {{ user.profile.age }}</p>
              <p class="text-center">Email: {{ user.email }}</p>
              <p class="text-center">Biography: {{ user.profile.bio }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-9">
          <!-- User's Uploaded Posts -->
          <div class="bg-white shadow rounded-lg">
            <div class="p-4">
              <h3 class="mb-4">Your Uploaded Posts</h3>
              <!-- Loop through and display the user's uploaded posts -->
              <div class="row">
                {% for post in posts %}
                <div class="col-md-6 mb-3">
                  <div class="card">
                    <img src="{{ post.image_files.first.image.url }}" class="card-img-top" alt="{{post.titlee}}">
                    <div class="card-body">
                      <h5 class="card-title">{{ post.title }}</h5><hr>
                      <p class="card-text">{{ post.content|truncatewords:30 }}</p>
                      <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></script>
    <script>
      $.ajaxSetup({
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
        },
      });
    </script>
    <script>
      // Function to remove the messages after 5 seconds
      function removeMessages() {
          setTimeout(function() {
              var messagesContainer = document.getElementById('messages-container');
              if (messagesContainer) {
                  messagesContainer.innerHTML = '';
              }
          }, 5000); // 5000 milliseconds = 5 seconds
      }

      // Call the function when the document is ready
      document.addEventListener("DOMContentLoaded", function() {
          removeMessages();
      });
  </script>

  </body>
</html>

accounts/templates/accounts/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit profile</title>
</head>
<body>
    <h1>Edit Your Profile</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% for error in form.age.errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}
        <button type="submit">Edit</button>
    </form>
</body>
</html>

accounts/templates/accounts/input_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-7">
                <div class="card bg-primary mt-5">
                    <div class="card-body">
                        <h1 class="card-title">Forgot your password?</h1>
                        <h5 class="card-text">No problem! Just fill in the email below, and we'll send you password reset instructions.</h5>
                        <form id="password-reset-form" action="{% url 'accounts:reset_password' %}" method="post">
                            <div class="mb-3">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>
                            <button type="submit" class="btn btn-primary">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Include Bootstrap JS and jQuery -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

accounts/templates/accounts/notifications.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>notification</title>
</head>
<body>
    {% for notification in notifications reversed  %}
    <div class="{% if notification.viewed %}viewed{% else %}unviewed{% endif %}">
        <img src="{% if notification.user.profile.image %}{{ notification.user.profile.image.url }}{% else %}{{ notification.user.profile.get_image_display }}{% endif %}" alt="Profile Picture">
        {{ notification.message | safe  }} <br><hr>
        {{ notification.post.pk }} {{ notification.post.slug }}
        Date: {{ notification.timestamp|timesince  }} <br>
    </div>
    {% endfor %}
</body>
</html>

accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset password complete</title>
</head>
<body>
{% block content %}
    <p>your password changed.</p>
{% endblock %}
</body>
</html>

accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>reset confirm </title>
</head>
<body>
    {% if validlink %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
    {% else %}
        <p>this link is not valid. please try again.</p>
    {% endif %}
</body>
</html>

accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rest done </title>
</head>
<body>
    <p>we sent you an email</p>
</body>
</html>

accounts/templates/accounts/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0-beta3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css\signup.css' %}" >
  <title>Register</title>
</head>
<body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 mt-5">
        <div class="card">
          <div class="card-header rounded-3">
            <h3 class="text-center" >Create an Account</h3>
          </div>
          <div class="card-body">
            <form action="{% url 'accounts:user_register' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
               </div>
              <div class="d-grid">
                <button type="submit" act class="btn btn-primary rounded-3 ">Sign Up</button>
              </div>
            </form>
          </div>
          <div class="card-footer text-center rounded-3 ">
            <p class="text">Already have an account? <a href="{% url 'accounts:user_login'%}">Log In</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.0-beta3/js/bootstrap.bundle.min.js"></script>
</body>
</html>