accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name = 'user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('follow/<int:user_id>/' , views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('notifications/', views.NotificationListView.as_view(), name='notification_list'),


    
]

posts/urls.py
from django.urls import path
from . import views


app_name ='posts'

urlpatterns = [
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create', views.PostcreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.LikePostView.as_view(), name='post_like'),
    path('unlike/<int:post_id>/', views.UnlikePostView.as_view(), name='post_unlike'),
    path('tag/<slug:tag_slug>/', views.TaggedPostsView.as_view(), name='tagged_posts'),

]

zab/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path ('posts', include('posts.urls')),
    
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from django.utils.text import slugify

class Image (models.Model):
    image = models.ImageField(upload_to='blog/', null=True,blank=True, default='static/img/defult.jpg')
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='image_files')

class Video(models.Model):
    video = models.FileField(upload_to='blog/',null=True, blank=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE , related_name='videos_files')

class Audio(models.Model):
    audio = models.FileField(upload_to='blog/', null=True, blank=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE , related_name='audios_files')

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    file = models.ManyToManyField(Image, related_name='associated_posts', blank=True) 
    videos = models.ManyToManyField(Video, related_name='associated_posts', blank=True)
    audios = models.ManyToManyField(Audio, related_name='associated_posts', blank=True)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    slug = models.SlugField()
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
         ordering = ['-created_date', '-counted_views']

    def __str__(self):
        return f'{self.title} - {self.slug} - {self.created_date}'
    
    def get_absolute_url(self):
        print("PK:", self.pk)
        print("Slug:", self.slug)
        url = reverse('posts:post_detail', args=[str(self.pk), self.slug])
        print("Generated URL:", url)
        return url
    
    def user_can_like(self, user):
        return user.uvotes.filter(post=self).exists()
    

    

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply_comments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    comment = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.author.username} on {self.post.title}"


class vote(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='uvotes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

    def __str__(self):
        return f'{self.author} liked {self.post}'
    

	


        

posts/forms.py
from django import forms
from .models import Post, Comment , Image, Video,Audio
from django.forms.widgets import ClearableFileInput

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class PostUpdateCreateForm(forms.ModelForm):
    image = forms.FileField(widget=MultipleFileInput(), required=False)
    video = forms.FileField(widget=MultipleFileInput(), required=False)
    audio = forms.FileField(widget=MultipleFileInput(), required=False)
    
    class Meta:
        model = Post
        fields = ('image', 'video', 'audio', 'title', 'content', 'tags')

    def save(self, commit=True):
        post = super().save(commit=commit)

        image_files = self.cleaned_data.get('image')
        video_files = self.cleaned_data.get('video')
        audio_files = self.cleaned_data.get('audio')

        if image_files:
            for image in image_files:
                Image.objects.create(post=post, image=image)
        if video_files:
            for video in video_files:
                Video.objects.create(post=post, video=video)
        if audio_files:
            for audio in audio_files:
                Audio.objects.create(post=post, audio=audio)
        return post
		
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
	


class CommentReplyForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

posts/views.py
from typing import Any
from django import http
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from .models import Post, Comment, vote , Image, Audio, Video
from django.http import JsonResponse
from .forms import PostUpdateCreateForm , CommentCreateForm, CommentReplyForm
from taggit.models import Tag
from django.utils.text import slugify
from django.template.defaultfilters import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def get(self, request, post_id, post_slug):
        post_instance = get_object_or_404(Post, pk=post_id, slug=post_slug)
        comments = post_instance.post_comments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and post_instance.user_can_like(request.user):
            can_like = True

        can_unlike = False
        if request.user.is_authenticated and vote.objects.filter(author=request.user, post=post_instance).exists():
            can_unlike = True

        form = self.form_class()
        reply_form = self.form_class_reply()

        likes_count = vote.objects.filter(post=post_instance).count()
        tags = post_instance.tags.all()

        return render(request, 'posts/detail_post.html', {
            'post': post_instance,
            'comments': comments,
            'form': form,
            'reply_form': reply_form,
            'can_like': can_like,
            'can_unlike': can_unlike,
            'likes_count': likes_count,
            'tags': tags,
        })

    @method_decorator(login_required)
    def post(self, request, post_id, post_slug):
        post_instance = get_object_or_404(Post, pk=post_id, slug=post_slug)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post_instance
            new_comment.save()
            messages.success(request, 'Your comment has been submitted successfully.', extra_tags='success')
            

            form = self.form_class()
        
        comments = post_instance.post_comments.filter(is_reply=False)
        reply_form = self.form_class_reply()

        return render(request, 'posts/detail_post.html', {
            'post': post_instance,
            'comments': comments,
            'form': form,
            'reply_form': reply_form,
            
        })


class PostDeleteView(LoginRequiredMixin, View):
    def get (self, request, post_id):
        post= get_object_or_404(Post , pk=post_id)
        if post.author.id == request.user.id:
            post.delete()
            messages.success(request, 'post delete ')
        else:
            messages.error(request, 'you can not post delete')
        return redirect('home:home')
    



class PostUpdateView(LoginRequiredMixin, View):

    def setup(self, request, *args: Any, **kwargs: Any):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, post_id):
        post = self.post_instance
        if post.author.id == request.user.id:
            form = PostUpdateCreateForm(instance=post)
            return render(request, 'posts/update.html', {'form': form, 'post': post})
        else:
            messages.error(request, 'You cannot update this post.', 'danger')
            return redirect('home:home')

    def post(self, request, post_id):
        post = self.post_instance
        if post.author.id == request.user.id:
            form = PostUpdateCreateForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                post.title = form.cleaned_data['title']
                post.slug = slugify(post.title)
                post.save()
                messages.success(request, 'Post updated successfully.')
                return redirect('posts:post_detail', post_id=post.id, post_slug=post.slug)
            else:
                messages.error(request, 'Failed to update the post.', 'danger')
                return render(request, 'posts/update.html', {'form': form, 'post': post})
        else:
            messages.error(request, 'You cannot update this post.', 'danger')
            return redirect('home:home')
        


class PostcreateView(LoginRequiredMixin, View):
    form_class = PostUpdateCreateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        tags = Tag.objects.all()
        return render(request, 'posts/create_post2.html', {'form': form, 'tags': tags})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['title'][:30])
            new_post.author = request.user
            new_post.save()

            image_files = request.FILES.getlist('image')  # Retrieve a list of uploaded image files
            video_files = request.FILES.getlist('video')  # Retrieve a list of uploaded video files
            audio_files = request.FILES.getlist('audio')  # Retrieve a list of uploaded audio files

            try:
                for image_file in image_files:
                    Image.objects.create(post=new_post, image=image_file)
                for video_file in video_files:
                    Video.objects.create(post=new_post, video=video_file)
                for audio_file in audio_files:
                    Audio.objects.create(post=new_post, audio=audio_file)
            except Exception as e:
                print("Error during file creation:", e)

            form.save_m2m()

            messages.success(request, 'You created a new post', 'success')
            return redirect('posts:post_detail', new_post.id, new_post.slug)

        return render(request, 'posts/create_post2.html', {'form': form, 'tags': Tag.objects.all()})

class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post_instance = get_object_or_404(Post, id=post_id)
        comment_instance = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.author = request.user
            reply.post = post_instance
            reply.reply = comment_instance
            reply.is_reply = True
            reply.save()
        return redirect('posts:post_detail', pk=post_instance.pk, slug=post_instance.slug)
    
class LikePostView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like, created = vote.objects.get_or_create(author=request.user, post=post)
        if not created:
            like.delete()
        return redirect('posts:post_detail', post.id, post.slug)
    
class UnlikePostView(LoginRequiredMixin, View):
    def unlike_post(self, request, post):
        try:
            existing_like = vote.objects.get(author=request.user, post=post)
            existing_like.delete()
        except vote.DoesNotExist:
            pass
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        if request.method == "GET" and request.user.is_authenticated:
            self.unlike_post(request, post)
            return redirect('posts:post_detail', post_id=post_id, post_slug=post.slug)
        return redirect('posts:post_detail', post_id=post_id, post_slug=post.slug)
    
class TaggedPostsView(View):
    template_name = 'posts/tagged_posts.html'

    def get(self, request, tag_slug):
        tag = Tag.objects.get(slug=tag_slug)  # Retrieve the tag object
        tagged_posts = Post.objects.filter(tags=tag)  # Filter posts by the tag
        return render(request, self.template_name, {'tagged_posts': tagged_posts})


    

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="{% url 'posts:post_create'%}" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="file" name="image">
        <input type="file" name="video">
        <input type="file" name="audio">
        <input type="submit" value="Create post">
    </form>
{% endblock %}

posts/templates/posts/create_post2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Create Post</title>
  <link rel="stylesheet" href="{% static 'css\create_post.css' %}">
  <!-- Link to Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <style>
    body {
      background-color: #f8f9fa;
    }
    .card {
      background: rgb(18, 100, 233);
      border: none;
      box-shadow: 0 2px 4px rgba(55, 48, 48, 0.1);
    }
    .btn-primary {
      background-color: rgb(18, 100, 233) ;
      border-color: #0e78ea;
    }
  </style>
</head>
<body>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Create a New Post</h4>
          <form enctype="multipart/form-data" method="post" action="{% url 'posts:post_create' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="photos" class="form-label">Upload Files</label>
                {{ form.image }}
            </div>
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                {{ form.title }}
            </div>
            <div class="mb-3">
                <label for="text" class="form-label">Text</label>
                {{ form.content }}
            </div>
            <div class="mb-3">
                <label for="tags" class="form-label">Tags</label>
                {{ form.tags }}
                <small class="form-text text-muted">Separate tags with commas.</small>
            </div>
            <button type="submit" class="btn btn-primary">Create Post</button>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Link to Bootstrap JS and Popper.js (required for Bootstrap features) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

posts/templates/posts/detail_post.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{{ post.title }}</title>
    <style>
        /* Add your CSS styles here */
        .post {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .post-title {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .post-image {
            width: 100%;
            height: auto;
            margin-bottom: 20px;
        }

        .post-content {
            margin-bottom: 20px;
        }

        .post-metadata {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .post-view-count,
        .post-author {
            font-size: 14px;
        }

        .post-media {
            margin-bottom: 20px;
        }

        .post-buttons {
            text-align: right;
            margin-bottom: 20px;
        }

        a{
            text-decoration: none;

        }

    </style>
</head>
<body>
    <div class="post">
        <div class="post-buttons">
            {% if post.author == request.user %}
                <a href="{% url 'posts:post_delete' post.id %}"><button class="btn btn-outline-dark mt-3">Delete Post</button></a>
                <a href="{% url 'posts:post_update' post.id %}"><button class="btn btn-outline-dark mt-3">Update Post</button></a>
            {% endif %}
            
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'posts:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} btn btn-primary col-md-2">Like {{ likes_count }}</a>
            <a href="{% url 'posts:post_unlike' post.id %}" class="btn btn-danger col-md-2">Unlike</a>
        {% endif %}

        <div class="post-metadata mt-3">
            <span class="post-view-count fw-bold"> Views: {{post.counted_views}} </span>

            <a href="{% url 'accounts:user_profile' post.author.id  %}">Author: <span class="post-author fw-bold ">{{post.author}} </span></a>
        </div>
          <!-- Include Bootstrap JS (Optional) -->
          <h1 class="post-title">{{ post.title }}</h1>

          <div class="post-images">
              {% for image_file in post.image_files.all %}
                  <img class="post-image" src="{{ image_file.image.url }}" alt="{{ post.title }}">
              {% endfor %}
          </div>
          
          <div class="post-content">
              <p>{{ post.content }}</p>
          </div>
          
          <div class="post-media">
              <h2>Related Media</h2>
              <div class="post-videos">
                  {% for video_file in post.videos_files.all %}
                      <video controls>
                          <source src="{{ video_file.video.url }}" type="video/mp4">
                          Your browser does not support the video tag.
                      </video>
                  {% endfor %}
              </div>
              
              <div class="post-audios">
                  {% for audio_file in post.audios_files.all %}
                      <audio controls>
                          <source src="{{ audio_file.audio.url }}" type="audio/mpeg">
                          Your browser does not support the audio tag.
                      </audio>
                  {% endfor %}
              </div>
          </div>
          <!-- Include Bootstrap JS (Optional) -->

          <h5>Tags:</h5>
          <ul>
            {% for tag in post.tags.all %}
                <li><a href="{% url 'posts:tagged_posts' tag_slug=tag.slug %}"> {{ tag }} </a></li>
            {% endfor %}
              
          </ul>

        <h3>Comments</h3>
<div class="list-group">
    {% for comment in comments %}
        <div class="list-group-item">
            <p class="mb-1">{{ comment.comment }}</p>
            <small class="text-muted">Posted by {{ comment.author }} on {{ comment.created|timesince }}</small>
        </div>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
</div>

<hr>

<h3>Add a Comment</h3>
<form method="post" action="{% url 'posts:post_detail' post.id post.slug %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Post Comment</button>
</form>

{% if request.user.is_authenticated and comment %}
    <h3>Reply to Comment</h3>
    <form method="post" action="{% url 'posts:add_reply' post.id comment.id %}">
        {% csrf_token %}
        {{ reply_form.as_p }}
        <button type="submit">Post Reply</button>
    </form>
{% endif %}

{% with replies=comment.reply_comments.all %}
    {% for reply in replies %}
        <p>{{ reply.author }} <br/> {{ reply.comment }}</p>
    {% endfor %}
{% endwith %}

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/multiple_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Multiple File Upload</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center">Multiple File Upload</h1>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Upload Files</h5>
                <form action="#" method="post" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="files" class="form-label">Select multiple files</label>
                        <input type="file" class="form-control" id="files" name="files[]" multiple required>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

posts/templates/posts/tagged_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include 'inc/navbar.html' %}
    <h5 class="text-center mt-3">Posts related to your selected tag</h5>

    <div class="row">
        {% for post in tagged_posts %}
            <div class="col-lg-4 col-md-6">
                <div class="card mb-4">
                    <img src="{{ post.image_files.first.image.url }}" class="card-img-top" alt="{{ post.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</a></h5>
                        <p class="card-text">{{ post.content|truncatewords:8 }}</p>
                        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More</a>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 or forloop.last %}
                </div>
                {% if not forloop.last %}
                    <div class="row">
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>

posts/templates/posts/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="post" action="{% url 'posts:post_update' post.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}